### ISSUE TITLE
感谢作者的开源，请教两个问题，不知道是否方便

### ISSUE THREAD

**Issue by sineom-1** [gcui-art/album-ai#1]
1. 使用4o，一张图大概得费用是多少呢？
2. RAG API 是将图像的原数据存储在服务端吗？

**Comment by blueeon** [comment]
> 1. 使用4o，一张图大概得费用是多少呢？
> 2. RAG API 是将图像的原数据存储在服务端吗？
---
1. 512X512，$0.000425/per
2. RAG workflow: image -> meatedata(string) -> embedding(openai) -> PGSQL (pvector)
