### ISSUE TITLE
Optimize the return values of vector queries by filtering out results with low similarity scores.

### ISSUE THREAD

**Issue by blueeon** [gcui-art/album-ai#5]
**Is your feature request related to a problem? Please describe.**
The query will return images with very low relevance.

**Describe the solution you'd like**
1. Filter out irrelevant images, and if there are no related images, inform that none were found.
2. Relevance scoring can be a configuration.

**Additional context**
For example, when searching for "shoes", the image gallery does not contain pictures of shoes, yet it still returns results.

**Comment by linkly-ai** [comment]
Just now supported, but for running services, DB may need to drop and initialize.

Drop DB:
`rm -rf /tmp/postgres`

**Comment by GitPusher99** [comment]
Just now supported, but for running services, DB may need to drop and initialize.

Drop DB:
`rm -rf /tmp/postgres`

**Comment by blueeon** [comment]
Test:
<img width="758" alt="image" src="https://github.com/user-attachments/assets/75b6d780-1085-45df-9aaa-a72f30199758">
